Fix: Remove Service.Protocol.ALL case not supported in upstream
The Service.Protocol enum in upstream/master does not have ALL defined yet,
so the switch statement should not include a case for it. This will be added
in a separate PR.

Fixes compilation error: "an enum switch case label must be the unqualified
name of an enumeration constant"