CompositeBatfishException: add suppressed exceptions (#912)
* Delete CompositeBatfishException

Replace the few places it was used with suppressed exceptions.