rules_jvm_external: upgrade to 6.6 and fix new compiler error
```
projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/VerboseEdgeTest.java:20: error: [SelfAssertion] You are passing identical arguments to the assertEquals method, so this assertion always passes. THIS IS LIKELY A BUG! If you are trying to test the correctness of an equals() implementation, use EqualsTester instead.
    assertEquals(edge1, edge1);
                ^
    (see https://errorprone.info/bugpattern/SelfAssertion)
```

commit-id:62392438